name: GitHub Actions Demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 
      
    - name: Test
      working-directory: ./LoanCalculator/go
      run: go test
