name: GitHub Actions Demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17 
      
    - name: Test
      working-directory: ./LoanCalculator/go
      run: go test
