name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: run linter
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: ../LoanCalculator
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
      
    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0.4.0
      with:
        working_directory: ../LoanCalculator/
        deliverables: ./app.yaml
        project_id: learned-shell-332900
        credentials: '${{ secrets.GCP_SA_KEY }}'
